version: "3.9"

services:
    app:
      image: todo-application
      ports:
        - 8080:8080

      environment:
        - DB_URL=jdbc:postgresql://0.0.0.0:5432/test_db
        - DB_USER=test_db
        - DB_PASSWORD=test_db
      network_mode: "host"
      depends_on:
        - test_db

    test:
      build:
        context: .
        dockerfile: Dockerfile
      expose:
        - 8081:8081
      environment:
        - DB_URL=jdbc:postgresql://0.0.0.0:5432/test_db
        - DB_USER=test_db
        - DB_PASSWORD=test_db
      depends_on:
        - app
        - chrome

      network_mode: "host"

    test_db:
      image: postgres:latest
      restart: always
      ports:
        - "5432:5432"
      expose:
        - 5432:5432
      environment:
        - POSTGRES_DB=test_db
        - POSTGRES_USER=test_db
        - POSTGRES_PASSWORD=test_db
        - POSTGRES_PORT=5432

      volumes:
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      network_mode: "bridge"

    chrome:
      image: seleniarm/standalone-chromium:latest
      ports:
        - 4444:4444

      shm_size: 3gb
      environment:
        START_XVFB: "false"
        SE_NODE_MAX_SESSIONS: 15
        SE_NODE_OVERRIDE_MAX_SESSIONS: "true"

      network_mode: "host"